from app.parser.cleaner import remove_boilerplate_lines
from app.parser.metadata import extract_metadata

def parse(raw_lines):
    metadata = extract_metadata(raw_lines)
    
    lines = [l.rstrip('\n\r') for l in raw_lines]
    no_boiler = remove_boilerplate_lines(lines)

    rows = []
    for line in no_boiler:
        stripped = line.strip()
        if not stripped: continue
        
        # Highly specialized shadow file parsing
        row = {
            "INSTNO": line[0:3].strip(),
            "ACCNO": line[3:20].strip(),
            "BRNO": line[20:25].strip(),
            "CIFNO": line[25:42].strip(),
            "NAME": line[42:102].strip(),
            "OPNDATE": line[102:110].strip(),
            "CURRENCY": line[110:113].strip(),
            "STATUS": line[113:115].strip(),
            "STPCHQIND": line[115:116].strip(),
            "CURRBAL": line[116:134].strip(),
            "AVLBAL": line[134:152].strip(),
            "ODLIMIT": line[152:170].strip(),
            "UNCLRAMT": line[170:188].strip(),
            "FROZAMT": line[188:206].strip(),
            "DRAWINGAMT": line[206:224].strip(),
            "ACCTYPE": line[224:228].strip(),
            "INTCAT": line[228:232].strip(),
            "ACCCODE": line[232:233].strip(),
            "MTDATE": line[233:241].strip(),
            "INTRATE": line[241:248].strip(),
            "SECIND": line[248:249].strip(),
            "SEGCODE" : line[249:253].strip(),
            "ACTCLOSEDT" : line[253:261].strip(),
            "SANCDATE" : line[261:269].strip(),
            "POSREST" : line[269:270].strip(),
            "HOLD" : line[270:271].strip(),
            "STOP" :line[271:272].strip(),
            "EXTNCTRID" : line[272:277].strip(),
            "NEWIRAC" : line[277:279].strip(),
            "OLDIRAC" :line[279:281].strip(),
            "DEPPRD" :line[281: 289].strip(),
            "REPACCCODE" : line[289:290].strip(),
            "A1" : line[290:308].strip(),
            "DATE": line[308:318].strip(),
            "A2" : line[318:336].strip(),
            "INTAVAIL": line[336:354].strip(),
            "A4": line[354:372].strip(),
            "A5": line[372:390].strip(),
            "A6": line[390:391].strip(),
            "A7" : line[391:401].strip(),
            "A8" : line[401:419].strip(),
            "A9" : line[419:424].strip(),
            "MOP1" : line[424:444].strip(),
            "NAME_1" : line[444:504].strip(),
            "N_1" : line[504:505].strip(),
            "N_2" :line[505:506].strip(),
            "SCHEMEDESC" : line[506: 546].strip(),
            "BRANCH" : line[546 : 551].strip(),
            "CURR" : line[551: 554].strip(), 
            "UNKNOWN": line[554:558].strip(),
            "UNKNOWN1" : line[558:564].strip(),
            "UNKNOWN2" :line[564 :571].strip(),
            "INTPD" :line[571:589].strip(),
            "INTCR" :line[589: 607].strip(),
            "UNKNOWN_ADDR":line[607:608].strip(),
            "ADDRESS1":line[608:648].strip(),
            "ADDRESS2": line[648:688].strip(),
            "ADDRESS3" :line[688:728].strip(),
            "ADDRESS4" : line[728:768].strip(),
            "PINCODE" :line[768:774].strip(),
            "MOB_NO": line[774:786].strip(),
        }
        rows.append(row)
        
    if not rows:
        dummy_row = {
            "INSTNO" : "",
            "ACCNO": "",
            "BRNO": "",
            "CIFNO": "",
            "NAME": "",
            "OPNDATE": "",
            "CURRENCY": "",
            "STATUS": "",
            "STPCHQIND": "",
            "CURRBAL": "",
            "AVLBAL": "",
            "ODLIMIT": "",
            "UNCLRAMT": "",
            "FROZAMT": "",
            "DRAWINGAMT": "",
            "ACCTYPE": "",
            "INTCAT": "",
            "ACCCODE": "",
            "MTDATE": "",
            "INTRATE": "",
            "SECIND": "",
            "SEGCODE" : "",
            "ACTCLOSEDT" : "",
            "SANCDATE" : "",
            "POSREST" : "",
            "HOLD" : "",
            "STOP" :"",
            "EXTNCTRID" : "",
            "NEWIRAC" : "",
            "OLDIRAC" : "",
            "DEPPRD" : "",
            "REPACCCODE" : "",
            "A1" : "",
            "DATE": "",
            "A2" : "",
            "INTAVAIL": "",
            "A4": "",
            "A5": "",
            "A6": "",
            "A7" : "",
            "A8" : "",
            "A9" : "",
            "MOP1" : "",
            "NAME_1" : "",
            "N_1" : "",
            "N_2" : "",
            "SCHEMEDESC" : "",
            "BRANCH" : "",
            "CURR" : "", 
            "UNKNOWN": "",
            "UNKNOWN1" : "",
            "UNKNOWN2" :"",
            "INTPD" : "",
            "INTCR" : "",
            "UNKNOWN_ADDR": "",
            "ADDRESS1": "",
            "ADDRESS2": "",
            "ADDRESS3" : "",
            "ADDRESS4" : "",
            "PINCODE" :"",
            "MOB_NO": "",
            "_IS_SCHEMA_ONLY": True
        }
        rows.append(dummy_row)
        
    return rows
